CREATE TABLE Sets(
  SetId INT IDENTITY(1001, 1) PRIMARY KEY,
  SetGenericName VARCHAR(255) NOT NULL,
  SetDeptCode VARCHAR(10) NOT NULL,
  SetCategoryCode VARCHAR(10) NOT NULL,
  SetCost DECIMAL(11, 2) DEFAULT NULL,
  NewSetCost DECIMAL(11, 2) DEFAULT NULL,
  SetDateReceived DATE DEFAULT NULL,
  SetSupplierName VARCHAR(255) DEFAULT NULL,
  SetPurchaseOrderNo VARCHAR(255) DEFAULT NULL,
  SetInvoiceNo VARCHAR(255) DEFAULT NULL,
  SetItemSpecs VARCHAR(1000) DEFAULT NULL,
  SetRemarks VARCHAR(255) DEFAULT NULL,
  ReceivingReport VARCHAR(255) DEFAULT NULL,
  Condemned BIT DEFAULT 0,
  Salvaged BIT DEFAULT 0,
  Deleted BIT DEFAULT 0
)
